model:
  target: net_factory(net_type=mcnet2d_v1, in_chns=1, class_num=4)
  params:
    encoder_name: efficientnet-b2
    encoder_weights: null
    in_channels: 1
    classes: 4
    activation: null

optimizer:
  target: torch.optim.Adam
  learning_rate: 0.0005
  weight_decay: 3e-5
  max_epoch: 2000
  max_iter: 30000
  warmup_iter: -1
  lr_scheduler: lambda

saliency_balancing_fusion:
  usage: true
  grid_size: 18

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 16
    num_workers: 8
    train:
      target: dataloaders.CardiacDataset.get_training
      params:
        location_scale: true
        modality:
          - bSSFP
        tile_z_dim: 1
    validation:
      target: dataloaders.CardiacDataset.get_validation
      params:
        modality:
          - bSSFP
        tile_z_dim: 1
    test:
      target: dataloaders.CardiacDataset.get_test
      params:
        modality:
          - LGE
        tile_z_dim: 1